tables:
  - name: beacon_api_eth_v1_beacon_committee
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "2023-09-05"
        to: "2024-04-08"
      holesky:
        from: "2023-12-25"
        to: "2024-04-08"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-08"
    tags:
      - Consensus layer
    quirks: >-
      Sometimes sentries may [publish different committees](https://github.com/ethpandaops/xatu/issues/288) for the same epoch.
  - name: beacon_api_eth_v1_events_attestation
    database: default
    excluded_columns: []
    hourly_partitioning: true
    date_partition_column: slot_start_date_time
    networks:
      mainnet:
        from: "2023-06-05"
        to: "2024-04-08"
      holesky:
        from: "2023-09-29"
        to: "2024-04-08"
      sepolia:
        from: "2023-09-01"
        to: "2024-04-08"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_blob_sidecar
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-03-13"
        to: "2024-04-08"
      holesky:
        from: "2024-02-07"
        to: "2024-04-08"
      sepolia:
        from: "2024-01-30"
        to: "2024-04-08"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_block
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-02-28"
        to: "2024-04-08"
      holesky:
        from: "2023-12-24"
        to: "2024-04-08"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-08"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_chain_reorg
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-03-01"
        to: "2024-04-08"
      holesky:
        from: "2024-02-05"
        to: "2024-04-08"
      sepolia:
        from: "2024-04-03"
        to: "2024-04-03"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_contribution_and_proof
    database: default
    excluded_columns: []
    date_partition_column: contribution_slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-31"
        to: "2024-04-08"
      holesky:
        from: "2023-12-24"
        to: "2024-04-08"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-08"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_finalized_checkpoint
    database: default
    excluded_columns: []
    date_partition_column: epoch_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-04-10"
        to: "2024-04-08"
      holesky:
        from: "2023-03-26"
        to: "2024-04-08"
      sepolia:
        from: "2023-03-26"
        to: "2024-04-08"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_head
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-30"
        to: "2024-04-08"
      holesky:
        from: "2023-12-05"
        to: "2024-04-08"
      sepolia:
        from: "2023-12-05"
        to: "2024-04-08"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_events_voluntary_exit
    database: default
    excluded_columns: []
    date_partition_column: epoch_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-01-01"
        to: "2024-03-25"
      holesky:
        from: "2023-10-02"
        to: "2023-10-04"
      sepolia:
        from: Coming soon!
        to: Coming soon!
    tags:
      - Consensus layer
  - name: beacon_api_eth_v1_validator_attestation_data
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-31"
        to: "2024-04-08"
      holesky:
        from: "2023-12-24"
        to: "2024-04-08"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-08"
    tags:
      - Consensus layer
  - name: beacon_api_eth_v2_beacon_block
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-11-14"
        to: "2024-04-07"
      holesky:
        from: "2023-12-24"
        to: "2024-04-07"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-07"
    tags:
      - Consensus layer
  - name: mempool_transaction
    database: default
    excluded_columns: []
    date_partition_column: event_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-07-22"
        to: "2024-04-08"
      holesky:
        from: "2024-01-08"
        to: "2024-04-08"
      sepolia:
        from: "2024-01-08"
        to: "2024-04-08"
    tags:
      - Execution layer
      - Transaction
      - Mempool
  - name: beacon_api_eth_v1_proposer_duty
    database: default
    excluded_columns: []
    hourly_partitioning: false
    date_partition_column: slot_start_date_time
    networks:
      mainnet:
        from: "2024-04-03"
        to: "2024-04-04"
      holesky:
        from: "2024-04-03"
        to: "2024-04-04"
      sepolia:
        from: "2024-04-03"
        to: "2024-04-04"
    tags:
      - Consensus layer
  - name: canonical_beacon_block
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: "2023-09-28"
        to: "2024-04-08"
      sepolia:
        from: Coming soon!
        to: Coming soon!
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_attester_slashing
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: Coming soon!
        to: Coming soon!
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_proposer_slashing
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: Coming soon!
        to: Coming soon!
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_bls_to_execution_change
    database: default
    date_partition_column: slot_start_date_time
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: "2024-04-08"
        to: "2024-04-08"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_execution_transaction
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: Coming soon!
        to: Coming soon!
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_voluntary_exit
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: "2024-03-28"
        to: "2024-03-28"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_deposit
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: Coming soon!
        to: Coming soon!
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_block_withdrawal
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: "2023-02-28"
        to: "2024-04-08"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_blob_sidecar
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-03-13"
        to: "2024-04-08"
      holesky:
        from: "2024-02-07"
        to: "2024-04-08"
      sepolia:
        from: "2024-01-30"
        to: "2024-04-08"
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_proposer_duty
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: Coming soon!
        to: Coming soon!
    tags:
      - Consensus layer
      - Finalized
  - name: canonical_beacon_elaborated_attestation
    database: default
    excluded_columns: []
    date_partition_column: slot_start_date_time
    hourly_partitioning: true
    networks:
      mainnet:
        from: "2023-05-04"
        to: "2023-05-08"
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: "2023-04-06"
        to: "2024-04-08"
    tags:
      - Consensus layer
      - Finalized
