tables:
  - name: beacon_api_eth_v1_beacon_committee
    database: default
    excluded_columns: []
    hourly_partitioning: true
    networks:
      mainnet:
        from: "2023-09-05"
        to: "2024-04-05"
      holesky:
        from: "2023-12-25"
        to: "2024-04-05"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-05"
    quirks: >-
      Sometimes sentries may [publish different committees](https://github.com/ethpandaops/xatu/issues/288) for the same epoch.
  - name: beacon_api_eth_v1_events_attestation
    database: default
    excluded_columns: []
    hourly_partitioning: true
    networks:
      mainnet:
        from: "2023-06-05"
        to: "2024-04-05"
      holesky:
        from: "2023-09-29"
        to: "2024-04-05"
      sepolia:
        from: "2023-09-01"
        to: "2024-04-05"
  - name: beacon_api_eth_v1_events_blob_sidecar
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-03-13"
        to: "2024-04-05"
      holesky:
        from: "2024-02-07"
        to: "2024-04-06"
      sepolia:
        from: "2024-01-30"
        to: "2024-04-06"
  - name: beacon_api_eth_v1_events_block
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-02-28"
        to: "2024-04-05"
      holesky:
        from: "2023-12-24"
        to: "2024-04-06"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-06"
  - name: beacon_api_eth_v1_events_chain_reorg
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-03-01"
        to: "2024-04-05"
      holesky:
        from: "2024-02-05"
        to: "2024-04-06"
      sepolia:
        from: "2024-04-03"
        to: "2024-04-03"
  - name: beacon_api_eth_v1_events_contribution_and_proof
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-31"
        to: "2024-04-05"
      holesky:
        from: "2023-12-24"
        to: "2024-04-06"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-06"
  - name: beacon_api_eth_v1_events_finalized_checkpoint
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-04-10"
        to: "2024-04-05"
      holesky:
        from: "2023-03-26"
        to: "2024-04-06"
      sepolia:
        from: "2023-03-26"
        to: "2024-04-06"
  - name: beacon_api_eth_v1_events_head
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-30"
        to: "2024-04-05"
      holesky:
        from: "2023-12-05"
        to: "2024-04-06"
      sepolia:
        from: "2023-12-05"
        to: "2024-04-06"
  - name: beacon_api_eth_v1_events_voluntary_exit
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2024-01-01"
        to: "2024-03-25"
  - name: beacon_api_eth_v1_validator_attestation_data
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-08-31"
        to: "2024-04-05"
      holesky:
        from: "2023-12-24"
        to: "2024-04-06"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-06"
  - name: beacon_api_eth_v2_beacon_block
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: "2023-11-14"
        to: "2024-04-05"
      holesky:
        from: "2023-12-24"
        to: "2024-04-06"
      sepolia:
        from: "2023-12-24"
        to: "2024-04-06"
  - name: mempool_transaction
    database: default
    excluded_columns: []
    hourly_partitioning: false
    networks:
      mainnet:
        from: Coming soon!
        to: Coming soon!
      holesky:
        from: Coming soon!
        to: Coming soon!
      sepolia:
        from: Coming soon!
        to: Coming soon!
    tags:
      - Execution layer
      - Transaction
      - Mempool
