name: Trigger homepage deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy hook
        run: |
          curl -X POST "${{ secrets.HOMEPAGE_HOOK_URL }}"
