name: Update config

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-availability:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Run update-availability script
        run: |
          ./update-availability.sh
      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Update data availability" || echo "No changes to commit" && exit 0
          git push
      - name: Trigger deploy hook
        run: |
          curl -X POST "${{ secrets.HOMEPAGE_HOOK_URL }}"
